from collections import namedtuple

Result = namedtuple('Result', ['steps', 'score', 'loss'])
# Experience = namedtuple('Experience',['state','action','next_state','reward'])
Sars = namedtuple('Sars',['s','a','r', 'sprime'])


_MAPS = {
 	"2x2": [
        "SF",
        "HG"
    ],
	"4x4": [
        "SFFF",
        "FHFH",
        "FFFH",
        "HFFG"
    ],
    "8x8": [
        "SFFFFFFF",
        "FFFFFFFF",
        "FFFHFFFF",
        "FFFFFHFF",
        "FFFHFFFF",
        "FHHFFFHF",
        "FHFFHFHF",
        "FFFHFFFG"
    ],
	"16x16":[
		'SFHFFFFFFFFFFFHF'
		, 'FFFFHFFFFFFFFFFF'
		, 'FFFFHFFFFHHFFFFH'
		, 'FFFFFFFFFHFFFFFF'
		, 'FFHFFFFFFFFHFFFF'
		, 'FFHFFFFFFFFHFFFH'
		, 'FFHHFFHHFFFFFFFF'
		, 'FFFFFFFFFFFFHHFH'
		, 'FFFFHFFHFFFFFFFF'
		, 'FFHFFFFFHHFFFFFF'
		, 'FFFHFFFFHFFHFHHF'
		, 'FFHFFFFFFHFFHFFF'
		, 'FFFFHFFHFFFFFFFF'
		, 'FFHFFFFHFHFFFFHF'
		, 'FFFFFHHFFFFFFFHF'
		, 'FFFFFFFFFFHFFFFG'
		],
	"32x32":[
		'SFFFFFFFHFFHHFFHFFFFFFFFFFFHFHFH'
		, 'FFHFHFFFFFFFHFHFHHHFHFFFFFHFFFFH'
		, 'FFHFHFFHHFFHFFFFHFFFFFFFFHFFFHFF'
		, 'FFHFHFHFHFFFFFFFFFFFFHFFFFHHHFHF'
		, 'FFFHFFFHFHHFHFHFFFFHFFHFFFFHFFHF'
		, 'FFFHFFFFHFFHFHFFFFFFHFHHHHFFFFFF'
		, 'HFFFFFFFFHHFHFHFFHHFFFFFFFFFFHFF'
		, 'HFHFFFFFFFFHHFFFFFHFHFFFFFFFFHFH'
		, 'FFFFFFFHHHFFFHHFHFFFFFFHFFHHHFHF'
		, 'FHFFFHFFFHHFFFHFFFHFFHFFFFFFFHFF'
		, 'HFFFFHFFFHFFFFFFHFFFFFFFHFFHFFFH'
		, 'FFFFHFFFFFHHFFFFFFHFHHHFFFFFHFFH'
		, 'FFFFFHFHHFHFHFHFFFFFFFFFFFFFFHFH'
		, 'FHFFFFHHFHFFHHFFFFFFFFFFFFFHHFFF'
		, 'FFFFFFFFFHHFFFFFFHFFFFFFFFHFFFFF'
		, 'FFHFHFFFFFHFFFFFHHHFHFFFFFHFFFHH'
		, 'FFFFFFFHHHHFFFFHFFFFFFFFFFFFFFHF'
		, 'FFHHHHHFFFFFFFFHFFFFFFFHHHFHFFHF'
		, 'FFFFFFFHHFFFFFFFHHFFFFHHFFFHFFFF'
		, 'FFFFFFFFFFFHFFFFFHFFFFFFFFFFFFFF'
		, 'FFFFHHFFFFFFFFHFFFFFFFFFFFFHFFFF'
		, 'FFFFFFFFFFFHHFFFFFFFHFFFFFHFFHFF'
		, 'FFFFFFHFFHFFHFFFFFFFFHFHFHFFFFFF'
		, 'HFFFHFFHFFFFFFFFHFFHFFFFHHFFFFFH'
		, 'FFFHFFHFFFFFFFFFFFFHFFFFHFFFFFFF'
		, 'FFFFFFFFFFFHHFHFHFHFFFFFHFFFFHFF'
		, 'FHHFFFHFFFFHFFFFHFFFFFHHFFFHHFFF'
		, 'HFFHFFHFFHHFFFFFFHFFFFHFFFFFFFFF'
		, 'HFFFFFFFFFFHFHFFFFFFFHFFFFFHFFFF'
		, 'HFFFFFFFFHFFFFFFHFFHFFFFFHFFFFFF'
		, 'FHFFHFFFFFFFFHFFFFFFHFFFFFFHHHFF'
		, 'FFHFFFFFFFFFFFFHHHFFFFFFFFFFFFFG'],
	"64x64":[
		'SFHHFFFFFFFHFHFFHFFFFFFFFHFHFHFFHFFFFFFFHFFFFFFFFFFHFFFHFHFFFFHF'
		, 'HFFFFFFFHFFFHFHFFHHFFFFFFHFFFHHFFFFFHFFHHHHFHFHFHFFFFFFFFFHFHFFF'
		, 'FFHFFFFFFFFHHHFFFFFFFFFFFHFHFFFFFFHFFFFFFFFFFFFFHFFFFHFFFFHFFFFH'
		, 'FFFFFFFFFFFFHFFHFFFFFFFFFFFFFFHFFFFFFHFFFFHFFFFFFFHFHFHFFFFFFHFF'
		, 'FHFFFFFHFFHFFFHFFFFFFFFFFFFFHFHFHFFFFFHFFFFHHFFFFFFFFFFHFHFFFFFH'
		, 'HFFHFFFFFHFFHHFFHFFFFHFFFFFFHFFHFFFHFFFFFFFFFHFFFFFFFFFFHFHFHFFF'
		, 'FFFFFFFFFFHFFFFHFFFHFFHFFFFFFFFFFFFFFFFFHHFHFFFFFHFFHFFHFFFHFFFF'
		, 'FFFFFHFFFFFHHFHFHFFFFFFFFFHFFFFFFFHFFFFHFFFFFFHFFHFFHFFFFFFHFHFF'
		, 'FHFFHFFFFFFFFFFHFFFFHHFFFFHFFFFFHHHFFFHFHFFHFFFFFHFFFHFFFFFFFHFF'
		, 'FFFFFFFFFFFFFFFFFFFFHHFFHFFFFFHFFFFFFFFFFFFFHFHFFFHHFFFFFFFHFFFH'
		, 'HFFFHFFFHFFFHFFFFFFFFHHFFFHHFFFFFHFFHHFHFFFHHFFFHHFHFFHFFFFFHFFF'
		, 'FFFFHHFFFHHFFFHFFFFFFFFFFFFHFFFFFFFFFFFFFFFHHHFFFFFHFFFHFFFHFHFF'
		, 'HFFHFFFFFFFFFFFFFFFFFFFFFFHFFFFHFFFFFFFFFHFFHFFFFFFFFFFFFFFFFFFF'
		, 'HFFFFFHHFFHFFFFFFFFHFFHFFFFFFFHFHHFHHFFHFFFFFFHFFFFFFFFFFFFFFFFF'
		, 'FFFHFFFFFFFFFHFFFFFFFFFFFHHFHFFHHFFFFHHFFFFFFHFFFFFFFFFFFFFFFFFH'
		, 'HFHFHFFHFFHHHHFFFFFHHFFFFFFFFFFFFFFFFHFFFFFFFHFHFFFFFFHFHFFFFFFF'
		, 'FFFHFFHHFFFFFFFHFFFHHHFFFFFFFHHFFFFHHFHFFFFFFFFHFFFFFFFHFHFHFHFF'
		, 'FFFFHFHFFFHFFFHFFFFFHFFHFHFFHFFFFFFFFFHHFFFHFFFHFFHFFFFFFFFFFFHF'
		, 'FFFFFHFFFHFHFHFFFFHFFFFHFFFFFFFFFHFFFFFFFFFHHFHFFFFFFFFFFHFHFFFH'
		, 'HFFFHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHHFFFHFFHFHFFFFHFFFFF'
		, 'FHFFFHFFFFFFFFFHFFFFHFFFHFHFFFHHFFFFFFHFHFHFFFHFFFFFFFHHHHFFFFFH'
		, 'HHFFFHFFFFFHFFFFFFFFFFHFFFFHFFFFHFFFFFFFFFFFFFFFHFFHFFFFFFFHFFFF'
		, 'HFFFFFFFFFFFFFFHFFFFFFFFFFFHFFFFFFFHFFFFFFHHFHHFFFFFFFFFFFFFFFHF'
		, 'FHFFFFFFFFFFFFHHHFFHFFFHFFFFHFFFFHFFFFHFFFFFHFFFFFFFFFHFFFFFFHHF'
		, 'HHFFFFFFFHFFHHFFFFFFFHFHHFFFHFFFFFHFHHFFHFFFFFFFFFFFFFFFFFFHFFFF'
		, 'FFFFHFHHFFFFFFFFFFHFHFFFFFFFFFFFFFFFFFFHFFFFFFFHFFFFFFFHFFHHHHFH'
		, 'HFFFFFHFHFFFFHHFHFFFFHFFFHFFFFHFFFFFFFHFFFFFFFHFFFHFFFFFFHFFFFFF'
		, 'FFFFFFFFFHHFFFFHFFFFFHFFFFFFFFFFFHFHFFFFFFHFFFHHFFHHFHHFFFFFFHFF'
		, 'HHHFHFFHFFFHFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFHHFFHFFFHHFFHFFHFFF'
		, 'FHFHFFFFHFHFFFFFFFFFFFFFHFFFHFFFFFFFFFFFFFFFFFFFFFFFFHHFFFFFFHFF'
		, 'HFFFFHHFHFFFFFFFFFFHFFFFHFFFHFHFHHFFFFFFFFFFHFFFFFHFHHFFFFHFFFFH'
		, 'FFFFHFFHFFFHFFFFFFFHHHFFFFFHFHHFFHFHFFFFFFHFFFFFFFFHHFFFFFFFFFFF'
		, 'FFFHFFHFFHFFFFHFHFHFFHFFFHHFHFFFFFFFFFFFFHFHFFFFFFHFFFFHFHFFFFFF'
		, 'FFFFHFFFFFFFFFFFFFFHFFHHHFFFFFHHFHHFFHFHFFFFFFFFFFFFFHFFFFHFFHFF'
		, 'FFFFFFFFFFFFFFFFFFHFFFHFFHFHFFFFFFFFFFFFFFFHFHHHFFHFFFFFFHHFFFFH'
		, 'FFHFFFFFHFFFFFFFFFHFFFFFFFFFHFFFFHFFFHFHFFFFFFHFHFFFHFFFFHHHFFFF'
		, 'FFFFFFFFFHFFFHHFFHFHFHFFFFFFHFFFFFFFFFFFHFFFHFHFFHFFFFHFFHFFFHFH'
		, 'FHFHFFFHFFFFFFHHHFHFFHFFFFHFFFFFHFFFFFFFFFFFFHFFFFFFHHFFHFHHFHFF'
		, 'FFFFFFFFFFFFFHHFFFFFFHFFFFFFFHFFFFFFFFFFFFFFFFFFHHFFFFFFFFFFFFHF'
		, 'FFHFFFFHFFFFFFFHFHFFFFFFHFFFHFHHFFFFFFFFFFFFFFFHFFHFHFHHHFFFFFFH'
		, 'FHFFFFFFFFFFFFFFFHFHFHFFFFFHFHFFFFFFFFFFHFFFFFFFFFFFFFFFFFFHFFFF'
		, 'FHFFFFHHFFFFFHHHHFFFHHFFHFHFFFFFFFFFFHFHFHFFFFHFHFFFFFFFFFFFFFFH'
		, 'FFFHFFFFHFFFFFHHHFFFFFHFHFFHHFFFFFFFFHFFFHFFFFFFFFHFFFFFHHFFFFFF'
		, 'HFFFFFHFFFHFHFFFFFFHFFFHFFFFFFFFFFFFFHFFHFFFFFFFFFHFFFFHHFHFFFHF'
		, 'FFFFFFFFFHFFHHFFHFFFHFFFHFFFFFHFFHFFFHFHFHFHFFFFFFFFHFFFHFFFFFFH'
		, 'FFFFFFHFFFFFHFFFFFFHFHHFHFFFFHHFFFFFFFFFFHFFFFFHFFFFFFFFFFFHFFFF'
		, 'FFHFFFFFFFFFFFFFFFFHFFFFFFHFHFFFFFFFFFHHFHFFFFFFFFFFFFFHFFFFFFFF'
		, 'FFFHFFFHFFFFHFFFFFFHHFFFFFFFFFFFFFFFFFFHFFFHFFFHHFFFFFFFFFFFFHFH'
		, 'FHFFHFFFFFFHFFFFFFHFFFHFHFFFFFFFFFFFFHFFFFFFFFFHFFFFFHHFFFFFFFFF'
		, 'FFFFFFFFHFFHHFFFFFFFFFFFHHFFFFFFFFFFFFHFFFHFHFHFHFHFFFFFFFFFFHFF'
		, 'FFHFHFFFFFFFFHFFFFHHFHFFFFFHFFFFFFFFFFFHFFHHFFFFHFFFHFHFFFFFFHHF'
		, 'FFFFFFHHFFFFHFFFHHFHFFHFFFFHFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFHFFHF'
		, 'FFFHFFFFFHFFFFFFFFFFFFHFFFHFHFHFFFFFFFFFHFFFFFHHFFFFHHFHHFFFFFHF'
		, 'HFFFFFFHHFFFHFFHFHFHFFFFFHHFHFFFFFFHFFFFFFFFFFFFHFFFFFFFFFFHFFFF'
		, 'FFFFFFFFFFFFFFFFFFFFHFFFFFFHFFHFFFHFFFFFFFFFFFFFFFFFFFFFFFFFFHFF'
		, 'HFFFFHFFFFFFFHHFFFFHFFFFFFFFFHFFHHFHFFFFHFHFFFFFFFFFFFFHFHFFFFFF'
		, 'FFHFFHFFFFFFFHFFFFHFFFFFFFFFHFHFFFFFFFFFFFFFFFFFHFFFHFFFFFFHFFFF'
		, 'HFFFHFHFFFFFFFFFHFFFFFFHHFFFHFHFFFHFFFFFFFHHFFFFFHFFFFFFFFHFFFFF'
		, 'FFFFFFFFFFFFFHFFFFFFFFHFFFFHFHFHFHFFFFFFHFFFFFFFFFFFFFHHFFFFFHFF'
		, 'FFFHFFFFHFFHFFHFFFFFFFFFFFFFFFFFFFHFFHFFFFFFFFFFFFFFFFFFFFFFFHFF'
		, 'FFHFHFFFFHFHFFHFFFFHHHFHFFFFFFHHFFFFFFHFFFFFHFFFFFFFHHHFFFFFFFFH'
		, 'HHFFFFFFHFFFHFHFFFFFFFFFHFHFFHFFFHFFFHFFFFFHFHFHHHFFFFFFFFFFFFFH'
		, 'FHFFFHHFFFHFFHFFFFFFFFHFFHFHFFFFFHFFFFFFFFFFFHFHFFFHFFFHFFFHFFFF'
		, 'FFFHFFFFFFFFFFFFFFHHFFFFFFFFHFFFFFHFFFFFFFFFFFFFFHFFFFFFFFFFFFFG'
		]
}
# left, down, right, up
_ACTIONS = ["\u2190", "\u2193", "\u2192", "\u2191"]